# Generated by Django 3.0.1 on 2020-03-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20200222_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.ManyToManyField(blank=True, to='course.Tag', verbose_name='课程标签'),
        ),
    ]
