# Generated by Django 3.0.1 on 2020-03-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20200304_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='h5_desc_css',
            field=models.TextField(blank=True, null=True, verbose_name='h5格式描述的css'),
        ),
    ]
