# Generated by Django 3.0.1 on 2020-03-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_course_h5_desc_css'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='h5_desc_css',
        ),
    ]
