# Generated by Django 3.0.1 on 2020-03-04 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0013_remove_course_h5_desc_css'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.Lesson', verbose_name='对应视频')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '播放记录',
                'verbose_name_plural': '播放记录',
                'db_table': 'geng_record',
                'ordering': ['-id'],
            },
        ),
    ]
