# Generated by Django 3.0.1 on 2020-03-04 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_playrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='playrecord',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='播放时间'),
            preserve_default=False,
        ),
    ]
