# Generated by Django 3.0.1 on 2020-03-04 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_playrecord_add_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playrecord',
            old_name='add_time',
            new_name='play_time',
        ),
    ]
