# Generated by Django 3.0.1 on 2020-04-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20200304_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='lesson',
            field=models.ManyToManyField(blank=True, related_name='lesson_chapter', to='course.Lesson', verbose_name='课时'),
        ),
        migrations.AlterField(
            model_name='course',
            name='chapter',
            field=models.ManyToManyField(blank=True, related_name='chapter_course', to='course.Chapter', verbose_name='课程的所有章节'),
        ),
    ]
