# Generated by Django 3.0.1 on 2020-04-06 23:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0018_courserecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courserecord',
            unique_together={('user', 'course')},
        ),
    ]
